#!/usr/bin/env node
'use strict';
const fs   = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'routes.json'), 'utf8'));

// Invert static map: URL → key (for index.html proxy key lookup)
const routeKeys = Object.fromEntries(
  Object.entries(data.static).map(([k, v]) => [v, k])
);

const lines = [
  '/* @routes-start — generated by scripts/build.js, do not edit manually */',
  'const ROUTE_KEYS = ' + JSON.stringify(routeKeys, null, 2) + ';',
  'const SPECIAL_KEYS = new Set(' + JSON.stringify(data.special) + ');',
  '/* @routes-end */',
];

const htmlPath = path.join(root, 'index.html');
let   html     = fs.readFileSync(htmlPath, 'utf8');
const updated  = html.replace(
  /\/\* @routes-start[\s\S]*?@routes-end \*\//,
  lines.join('\n')
);
if (updated === html) {
  console.error('ERROR: @routes-start marker not found in index.html');
  process.exit(1);
}
fs.writeFileSync(htmlPath, updated);
console.log(`\u2713 Synced ${Object.keys(data.static).length} routes into index.html`);
